name: 'marketing_analytics'
version: '1.0'
config-version: 2

profile: 'marketing_analytics'

model-paths: ["dbt/models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
